name = "Test"
type = "function"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 3
permissions = [
  "<https://bsc-dataseed.binance.org>",
  "<https://api.coingecko.com>"
]

[build]
dir = "build"
entry = "Test_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "Test.wasm"
command = "npm run build:release"
